### ISSUE TITLE
Practica 1 - Diagrama de clases

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-7-diagrama-de-clases-modelo-blockchain-equipopromastergamer777#1]
Subir la practica de diagrama de clases.

**Comment by JoseABCruz** [comment]
[Práctica 1 Diagramas con Clases(José Antonio Balbuena Cruz).pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-diagrama-de-clases-modelo-blockchain-equipopromastergamer777/files/11539294/Practica.1.Diagramas.con.Clases.Jose.Antonio.Balbuena.Cruz.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 1 Diagramas con Clases (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-diagrama-de-clases-modelo-blockchain-equipopromastergamer777/files/11539312/Practica.1.Diagramas.con.Clases.Federico.Victoriano.Sierra.pdf)

**Comment by Heidi-19** [comment]
[Práctica 1 Diagramas con Clases.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-diagrama-de-clases-modelo-blockchain-equipopromastergamer777/files/11539488/Practica.1.Diagramas.con.Clases.pdf)

**Comment by SANDRAVELASCO** [comment]
[Practica 1 Diagrama con clases (Sandra Gabriela Velasco Guzmán.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-diagrama-de-clases-modelo-blockchain-equipopromastergamer777/files/11539789/Practica.1.Diagrama.con.clases.Sandra.Gabriela.Velasco.Guzman.pdf)

**Comment by EdwinOrtiz1412** [comment]
Calificacion: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
